# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rosetta-Extensions
version:      0.01
version_from: 
installdirs:  site
requires:
    DBI:                           1
    Locale::KeyedText:             0.03
    Rosetta:                       0.14
    SQL::SyntaxModel:              0.16

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
